// <auto-generated />
using System;
using ASPMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPMVC.Migrations
{
    [DbContext(typeof(ASPMVCContext))]
    partial class ASPMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("ASPMVC.Models.Gun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("ProductionDate");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Gun");
                });
#pragma warning restore 612, 618
        }
    }
}
